version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: goalify-db
    environment:
      POSTGRES_DB: goalify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecurepassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 